/* Mock-only browser gate for interview and critique behavior/layout. */
'use strict';
const path=require('path');
const fs=require('fs');
const REPO=path.resolve(__dirname,'..');
const MATRIX=JSON.parse(fs.readFileSync(path.join(__dirname,'platform_browser_matrix.json'),'utf8'));
function puppeteer(){for(const x of [process.env.PUP_DIR,'puppeteer','/home/damienriehl/.npm/_npx/7d92d9a2d2ccc630/node_modules/puppeteer'].filter(Boolean)){try{return require(x);}catch(_){}}throw new Error('Puppeteer unavailable (set PUP_DIR or install puppeteer)');}
const harness='file://'+path.join(REPO,'app','chat','test.html');
const query={interview:'?view=chat&matter=m05&persona=m05.per.halvard&title=State%20v.%20Halvard&client=Devon%20Halvard&scenario=normal',critique:'?view=critique&matter=m05&title=Suppression%20Memo%20Critique'};
async function mode(page,large){await page.evaluateOnNewDocument((on)=>localStorage.setItem('sonsteng-type-lg',on?'1':'0'),large);}
async function layout(page){return page.evaluate(()=>{const visible=(e)=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};const inProduct=(e)=>!e.closest('#harness');const hs=[...document.querySelectorAll('h1,h2,h3,h4,h5,h6')].filter((e)=>visible(e)&&inProduct(e));let p=0,j=[];hs.forEach(h=>{const n=+h.tagName[1];if(p&&n>p+1)j.push(`h${p}->h${n}`);p=n});return{h1:hs.filter(h=>h.tagName==='H1').length,jumps:j,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,large:document.documentElement.classList.contains('type-lg'),controls:[...document.querySelectorAll('button,input,textarea,select')].filter((e)=>visible(e)&&inProduct(e)).map(e=>({text:(e.textContent||e.getAttribute('aria-label')||'').trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})).filter(x=>x.w<24||x.h<24)};} )}
async function run(){const pup=puppeteer(),browser=await pup.launch({executablePath:process.env.CHROME_BIN||process.env.CHROMIUM_PATH||'/snap/bin/chromium',headless:process.env.HEADLESS==='1',userDataDir:path.join('/tmp',`sonsteng-chat-${process.pid}`),args:['--no-sandbox','--disable-dev-shm-usage','--disable-crash-reporter','--disable-breakpad']});let fail=0,total=0;for(const vp of MATRIX.viewports)for(const large of [false,true])for(const surface of ['interview','critique']){total++;const page=await browser.newPage();await page.setViewport(vp);await mode(page,large);try{await page.goto(harness+query[surface],{waitUntil:'networkidle0',timeout:30000});await page.waitForSelector(surface==='interview'?'#composer-input':'#deliverable',{timeout:10000});
      if(surface==='interview'){await page.waitForFunction(()=>window.SonstengChat&&window.SonstengChat.getState()==='IDLE'&&sessionStorage.getItem('sonsteng_sess'),{timeout:10000});await page.evaluate(()=>window.SonstengChat.send('Please tell me what happened from the beginning.'));await page.waitForFunction(()=>window.SonstengChat&&window.SonstengChat.getTurns()===1,{timeout:15000});const reply=await page.$eval('#stream',e=>e.textContent);if(!reply.includes("It was late"))throw new Error('mock interview outcome changed');}
      else{await page.type('#deliverable','The stop should be suppressed because the officer lacked reasonable articulable suspicion. The icy road explains the observed movement.');await page.click('.paste button[type=submit]');await page.waitForSelector('.crit-card',{timeout:10000});const text=await page.$eval('#result-mount',e=>e.textContent);if(!text.includes('Issue framing')||!text.includes('26 / 40'))throw new Error('mock critique outcome changed');}
      const found=await page.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='LARGE TYPE');if(!b)return false;b.click();return b.getAttribute('aria-pressed')==='true'});if(!found)throw new Error('Large Type control missing or aria-pressed did not update');const got=await layout(page),errors=[];if(got.h1!==1)errors.push(`H1=${got.h1}`);if(got.jumps.length)errors.push(`heading jumps ${got.jumps}`);if(got.overflow>1)errors.push(`overflow ${got.overflow}px`);if(got.controls.length)errors.push(`undersize controls ${JSON.stringify(got.controls.slice(0,4))}`);if(!got.large)errors.push('Large Type class absent');if(errors.length)throw new Error(errors.join(' | '));console.log(`PASS ${surface} ${vp.name} ${large?'large-start':'baseline-start'}`);
    }catch(e){fail++;console.error(`FAIL ${surface} ${vp.name} ${large?'large':'baseline'} — ${e.message}`)}finally{await page.close();}}
  await browser.close();console.log(`CHAT/CRITIQUE SUMMARY ${total-fail}/${total} PASS`);process.exit(fail?1:0)}
run().catch(e=>{console.error('BROWSER GATE ERROR:',e.message);process.exit(1)});
